### ISSUE TITLE
Sample Tracking Updates

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#155]
This is an issue for updating the sample tracking calls based on the discussions happening at BTI on Dec 14, 2017

These will need more discussion and refinement before being officially added to BrAPI. 

New Calls
```
/sample-search{?sampleDbId}{?plateDbId}{?germplasmDbId}...
/sample/{sampleDbId}
/sample/{sampleDbId}/xref
/plate-search{?plateDbId}{?germplasmDbId}...
/plate/{plateDbId}
/plate/{plateDbId}/xref
/plate/{plateDbId}/samples
/plate/{plateDbId}/sample/{sampleDbId}
```

New Models
```
Plate
{
	plateDbId: (string)
	
	studyDbId: (string)
	
	xrefs: []
	
	plateType: (string)
	plateSize: (int)
	samples: []
}

Sample
{
	sampleDbId: (string)
	observationUnitDbId: (string)
	
	germplasmDbId: (string)
	studyDbId: (string)
	plotDbId: (string)
	plantDbId: (string)
	
	xrefs: []
	
	plateDbId: (string)
	plateIndex: (int)
	takenBy:  (string)
	sampleTimestamp:  (timestamp)
    sampleType:  (string)
    tissueType:  (string)
    notes:  (string)
}

Plate xref
{
	plateDbId:
	xrefId:
	xrefURL:
	xrefSystemId:
}

Sample xref
{
	sampleDbId:
	xrefId:
	xrefURL:
	xrefSystemId:
}
```
