### ISSUE TITLE
update documentaitonURL documentation

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#560]
Curently in [study](https://github.com/plantbreeding/BrAPI/blob/brapi-V2.1/Specification/BrAPI-Core/Studies/Schemas/StudyNewRequest.yaml) and [germplasm](https://github.com/plantbreeding/BrAPI/blob/brapi-V2.1/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmNewRequest.yaml) the documentation url field is described as : 
```
documentationURL:
          description: A URL to the human readable documentation of an object
          format: uri
          type: string
          example: https://wiki.brapi.org
```
It should be updated as : 
*germplasm*
````
documentationURL:
          description: A URL to the human readable description of a germplasm, such as a genebank web page
          format: uri
          type: string
          example: https://urgi.versailles.inrae.fr/faidare/germplasm?id=aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L1Y4V1JIWQ%3D%3D or https://www.crop-diversity.org/mgis/accession/01IDN150207
````
*study*
````
documentationURL:
          description: A URL to the human readable documentation of a study
          format: uri
          type: string
          example: https://urgi.versailles.inra.fr/ephesis/ephesis/viewer.do#trialCard/trialId=241
````
