### ISSUE TITLE
BrAPI V2.1 Minor Questions

### ISSUE THREAD

**Issue by chaneylc** [plantbreeding/API#562]
There is a typo in the program type enum:
 enum:
          - STANARD <-- should be standard
          - PROJECT

V2.1 introduces enforcing camel case for all data fields this can be applied to the following fields:
PUI (e.g mapPUI, assemblyPUI, I think there are many of these)
documentationURL
termURI, sourceURI, sourceURI, etc.

Is there a reason samples has a list of external references, this seems to be the only object that has a list of them.

**Comment by BrapiCoordinatorSelby** [comment]
>Is there a reason samples has a list of external references, this seems to be the only object that has a list of them.

@chaneylc 
I'm not sure what you are seeing? `externalReferences` _should_ be an array everywhere, Samples is correct. In fact, all BrAPI models should just be importing [ExternalReference.yaml](https://github.com/plantbreeding/BrAPI/blob/brapi-V2.1/Specification/Components/Schemas/ExternalReferences.yaml) so you shouldn't see any difference anywhere in the spec. Do you have a counter example you are comparing with Samples?

**Comment by chaneylc** [comment]
So what I'm noticing is that swagger hub is not generating external references as a list for: Variant, core/VariableBaseClass, CallSet, Reference, ReferenceSet, geno/VariableBaseClass, VariantSet, and PedigreeNode.

When checking CallSet I noticed that external reference is defined through a reference:
```
externalReferences:
 $ref: '#/components/schemas/ExternalReferences
```
      

And objects that have correctly generated code (with a list of external references) seem to be defined more explicitly:
```
externalReferences:
          description: An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.
          example:
          - referenceId: doi:10.155454/12341234
            referenceSource: DOI
          - referenceId: 75a50e76
            referenceSource: Remote Data Collection Upload Tool
          items:
            properties:
              referenceID:
                deprecated: true
                description: "**Deprecated in v2.1** Please use `referenceId`. Github issue number #460 \n<br>The external reference ID. Could be a simple string or a URI."
                type: string
              referenceId:
                description: The external reference ID. Could be a simple string or a URI.
                type: string
              referenceSource:
                description: An identifier for the source system or database of this reference
                type: string
            type: object
          title: ExternalReferences
          type: array
```

Definitely odd, since the reference seems to have the type: array component.
