### ISSUE TITLE
Indentation is incorrect for several schemas

### ISSUE THREAD

**Issue by daveneti** [plantbreeding/API#631]
Indentation is incorrect for several schemas. For example
```
x-brapi-metadata:
  primaryModel: true
  module: BrAPI-Core
  title: Trial
  description: A Trial represents a collection of Study objects, and the metadata associated with that collection. A Trial could represent a multi-location experiment, and could contain information related to publications and data licensing.
```

should be

```
x-brapi-metadata:
  primaryModel: true
  module: BrAPI-Core
title: Trial
description: A Trial represents a collection of Study objects, and the metadata associated with that collection. A Trial could represent a multi-location experiment, and could contain information related to publications and data licensing.
```
